'''https://projecteuler.net/problem=45
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle    Tn = n(n + 1)/2     1, 3, 6, 10, 15, ...
Pentagonal  Pn = n(3n - 1)/2    1, 5, 12, 22, 35, ...
Hexagonal   Hn = n(2n - 1)      1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.'''
from resources.useful_functions import is_hexagonal, is_pentagonal


def tph(MIN):
    '''Finds the first triangle number Tn where n is bigger than MIN that is
    also pentagonal and hexagonal.'''
    n = MIN + 1
    Tn = n*(n+1)//2
    while not (is_pentagonal(Tn) and is_hexagonal(Tn)):
        n += 1
        Tn = n*(n+1)//2
    # No numbers with the property in the range specified
    return n, Tn


if __name__ == '__main__':
    print(tph(0))  # 40755
    print(tph(285))  # 1533776805, 0.057s
