'''https://projecteuler.net/problem=45'''
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:

# Triangle    Tn = n(n + 1)/2     1, 3, 6, 10, 15, ...
# Pentagonal  Pn = n(3n - 1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn = n(2n - 1)      1, 6, 15, 28, 45, ...

# It can be verified that T_285 = P_165 = H_143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
from resources.useful_functions import is_hexagonal, is_pentagonal


def tph(lower):
    '''Finds the first triangle number tn where n is bigger than lower that is
    also pentagonal and hexagonal.'''
    n = lower + 1
    tn = n*(n+1)//2
    while not (is_pentagonal(tn) and is_hexagonal(tn)):
        n += 1
        tn = n*(n+1)//2
    return n, tn


if __name__ == '__main__':
    print(tph(0))  # 40755
    print(tph(285))  # 1533776805, 0.057s
