'''Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
'''


def sumEvenFibonacci(n):
    '''Sums the even numbers in the Fibonacci sequence up to n.
    '''
    a0, a1 = 1, 1
    suma = 0
    while a1 <= n:
        if a1 % 2 == 0:
            suma += a1
        a0, a1 = a1, a0 + a1
    return suma


if __name__ == "__main__":
    print(sumEvenFibonacci(4000000)) # 4613732